// 补充：文游剧本「UI 可见字段」的中→英词典。
// SCENARIO_EN（en-dict.generated.ts）覆盖 标题/题材/引言/属性/属性档位/开场/志向/结局基调；
// 但【事件池物品名】等散落在各剧本事件里的界面可见中文不在其中，英文模式下会原样显示中文。
// 这里补充：① 全内置剧本的物品名（itemsGained/itemsLost/requiresItem，约 83 条）
//          ② 若干关键界面可见中文短语（用户可见、非 general 短词，避免误替换）。
// 在 src/wenyou/i18n.ts 合并进 FLAT_EN，由 DOM 文本替换机制应用到 UI。
//
// 说明：AI 在回合中即时生成、词典之外的新物品名仍可能漏网，主要靠 textgame 的 system 语言指令约束；
//       此处覆盖静态/已知界面文案与物品。
export const SCENARIO_ITEMS_EN: Record<string, string> = {
  // ===== 物品名（全内置剧本） =====
  '灵兽': 'Spirit Beast',
  '飞刀': 'Throwing Knife',
  '降书': 'Letter of Surrender',
  '手枪': 'Pistol',
  '撬棍': 'Crowbar',
  '罐头': 'Canned Food',
  '鹦鹉': 'Parrot',
  '舰宠鼠': 'Ship\u2019s Pet Rat',
  '良民证': 'Good Citizen ID',
  '海燕号': 'The Petrel',
  '八音盒': 'Music Box',
  '退烧药': 'Fever Medicine',
  '净水片': 'Water-Purifying Tablets',
  '旧怀表': 'Old Pocket Watch',
  '本命飞剑': 'Bonded Flying Sword',
  '上古神器': 'Ancient Divine Artifact',
  '血炼魔器': 'Blood-Forged Demonic Artifact',
  '宗门信物': 'Sect Token',
  '家传残谱': 'Heirloom Fragmented Manual',
  '玄铁重剑': 'Black Iron Heavy Sword',
  '武学秘籍': 'Martial-Arts Secret Manual',
  '人皮面具': 'Human-Skin Mask',
  '兵法残卷': 'Fragmentary Art-of-War Scroll',
  '敌军密报': 'Enemy Intelligence',
  '主公印信': 'Lord\u2019s Seal',
  '传国玉玺': 'Imperial Jade Seal',
  '连环计图': 'Chain-of-Tricks Strategem Map',
  '盟军质子': 'Allied Hostage',
  '外星造物': 'Alien Artifact',
  '星图残片': 'Star-Chart Fragment',
  '黑石碎片': 'Black Stone Shard',
  '密写药水': 'Invisible Ink',
  '微型相机': 'Miniature Camera',
  '祖传海图': 'Heirloom Sea Chart',
  '古舰巨炮': 'Ancient Ship Cannon',
  '船医灵药': 'Ship Doctor\u2019s Medicine',
  '多嘴鹦鹉': 'Chatty Parrot',
  '七海全图': 'Chart of the Seven Seas',
  '简陋长矛': 'Crude Spear',
  '军训干粮': 'Military Rations',
  '防毒面具': 'Gas Mask',
  '漕运账册': 'Grain-Transport Ledger',
  '先帝密诏': 'Late Emperor\u2019s Secret Edict',
  '知音纸条': 'Kindred-Spirit Note',
  '白首之约': 'Pledge of a Lifetime Together',
  '凤纹玉佩': 'Phoenix-Pattern Jade Pendant',
  '九转金创药': 'Nine-Cycle Wound Salve',
  '草庐对策图': 'Thatched-Cottage Strategem Map',
  '宿敌的战书': 'Rival\u2019s Duel Challenge',
  '生态种子库': 'Ecological Seed Bank',
  '藏宝岛坐标': 'Treasure Island Coordinates',
  '赤鸢的酒袋': 'Crimson Kite\u2019s Wine Flask',
  '安全区地图': 'Safe-Zone Map',
  '信号源坐标': 'Signal-Source Coordinates',
  '政敌的把柄': 'Rival Politician\u2019s Leverage',
  '太后的懿旨': 'Empress Dowager\u2019s Decree',
  '对台的战帖': 'Rival Troupe\u2019s Challenge',
  '凤凰劫残稿': 'Phoenix Calamity Draft',
  '女主的把柄': 'Female Lead\u2019s Secret',
  '传国玉玺线索': 'Clue to the Imperial Jade Seal',
  '外戚谋逆名册': 'Consort-Clan Rebellion Roster',
  '半块青铜罗盘': 'Half Bronze Compass',
  '完整青铜罗盘': 'Complete Bronze Compass',
  '海军通行勋章': 'Navy Pass Badge',
  '海妖传说残页': 'Siren Legend Fragment',
  '宿敌的悬赏令': 'Rival\u2019s Bounty Notice',
  '门生故吏名录': 'Prot\u00e9g\u00e9s and Retainers Roster',
  '军阀赠的金条': 'Warlord\u2019s Gifted Gold Bar',
  '老琴师的相托': 'Old Luthier\u2019s Entrustment',
  '姨太太的妒恨': 'Concubine\u2019s Jealousy',
  '戏迷会的锦旗': 'Opera-Fan Club Banner',
  '太子赠的玉佩': 'Crown Prince\u2019s Jade Pendant',
  '原著剧透手札': 'Original-Novel Spoiler Notes',
  '政敌的私通密信': 'Rival\u2019s Treasonous Secret Letter',
  '摩根的航海笔记': 'Morgan\u2019s Sailing Notes',
  '名家亲传的本子': 'Master\u2019s Own Script Book',
  '报馆主笔的人情': 'Newspaper Editor\u2019s Favor',
  '达官的堂会请柬': 'Official\u2019s Private-Show Invitation',
  '灌制唱片的合约': 'Record-Pressing Contract',
  '对家伶人的把柄': 'Rival Actor\u2019s Secret',
  '一名忠心的眼线': 'A Loyal Informer',
  '太后宫里的暗线': 'Agent in the Empress Dowager\u2019s Palace',
  '压箱底的名角戏服': 'Prize Prima Donna Costume',

  // ===== 关键界面可见中文短语（用户可见、避免过短泛词误替换） =====
  '轻触，揭晓此生结局': 'Tap to reveal this life\u2019s ending',
  '成就解锁': 'Achievement unlocked',
  '正在书写你的结局…': 'Writing your ending\u2026',
  '再活一世': 'Live again',
  '换个人生': 'Another life',
  '命途留影': 'Fate in frames',
  '分享此刻': 'Share this moment',
  '导出存档': 'Export save',
  '退出本局': 'Quit run',
  '照此行事': 'Do as advised',
  '行囊': 'Satchel',
  '记忆': 'Memory',
  '目标进度': 'Goal progress',
  '命运正在落笔…': 'Fate is being written\u2026',
  '重试本回合': 'Retry this turn',
  '回到最新': 'Back to latest',
  '有新内容': 'New content',
  '点击跳过': 'Tap to skip',
  '命运抉择': 'Fate decision',
  '命途': 'Fate',
  '目标': 'Goal',
  '千世书': 'Thousand Lives',
  '已达': 'Reached',
  '上限，需晋阶突破方可提升': 'cap is reached; break through the next rank to raise it',
  '会员专属': 'Member exclusive',
  '托管中': 'Auto-playing',
  '去升级': 'Upgrade',
  '继续手动游玩': 'Keep playing manually',
};
