/**
 * 文游 i18n：跟随主 App 界面语言（cure_lang）自动适配。
 * 简体为源语言；繁体由 opencc 运行时转换（复用原 LangToggle 机制，改为外层语言驱动）；
 * 英文走本模块词典。不提供文游内独立语言切换（外层 LangSwitch 已是全 App 语言总控）。
 * ⚠ 会话/引擎/成就记录仍用源语言（避免本地化后 tone 匹配错位）；AI 叙事由后端按用户语言生成。
 */
import { useEffect, useRef } from 'react';
import { getLang } from '../i18n';
import { SCENARIO_EN } from './scenarios/en-dict.generated';
import { SCENARIO_ITEMS_EN } from './scenarios/en-items';
import { builtinScenarios } from './scenarios/index';

export const isEn = () => getLang() === 'en';

/** 引号内模板/代码路径里的手工翻译入口（native confirm 等非 DOM 场景；含剧本字段词典 FLAT_EN） */
export function wyT(zh: string): string {
  return isEn() ? (FLAT_EN[zh] ?? zh) : zh;
}

/** 界面静态文案 zh → en */
export const WY_EN: Record<string, string> = {
  // App
  '← 返回': '← Back',
  '返回剧情演绎': 'Back to Story Mode',
  '返回文游主页': 'Back to Story Home',
  '开始新游戏将覆盖未完成的「': 'Starting a new game will overwrite the unfinished "',
  '」进度，确定？': '" — continue?',
  // 通用
  '存档': 'Save',
  '重试': 'Retry',
  '重试本回合': 'Retry this turn',
  '返回': 'Back',
  '未知': 'Unknown',
  '全屏读卷': 'Fullscreen',
  '退出全屏': 'Exit fullscreen',
  '菜单': 'Menu',
  '显示卷文': 'Show text',
  '看全图': 'View art',
  '看全图（轻触画面恢复）': 'View art (tap to restore)',
  '已复制 ✓': 'Copied ✓',
  '复制文字版 ⎘': 'Copy text ⎘',
  '（已结束）': '(ended)',
  // Home
  '千世书': 'Thousand Lives',
  '千世书 · MIT License': 'Thousand Lives · MIT License',
  '一卷千世，活过千种人生': 'One scroll, a thousand lives',
  '落子无悔，步步皆命运': 'Every move, a destiny',
  '跳到主要内容': 'Skip to main content',
  '已历结局': 'Endings seen',
  '已历 ': 'Seen ',
  ' 结局': ' endings',
  '结局图鉴': 'Endings',
  '成就': 'Achievements',
  '命书阁 →': 'Archive →',
  '继续游玩': 'Continue playing',
  '进行中': 'In progress',
  '继续游戏': 'Continue game',
  '放弃本局': 'Discard run',
  '导入剧本': 'Import scenario',
  '选择 .json 文件导入（不会写？先下载示例剧本）': 'Pick a .json file to import (new here? download the example first)',
  '下载示例剧本': 'Download example scenario',
  '剧本文件长什么样？': 'What does a scenario file look like?',
  '导入的是一个 .json 文件，核心字段如下（下载示例剧本照着改就行）：': 'Import a .json file — here are the core fields (download the example and edit it):',
  '自建剧本': 'Create your own',
  '填表创建，不用碰代码': 'Fill a form — no code needed',
  'AI 生成剧本': 'AI generate scenario',
  '输入主题，AI 为你写剧本（Pro）': 'Enter a theme and the AI will write a scenario for you (Pro)',
  '✨ AI 生成新剧本': '✨ AI Generate New Scenario',
  '给一个主题，AI 会为你设计属性、结局与上百条支线，生成后加入剧本库。Pro 会员专属 · 每日限量。': 'Give a theme — AI designs attributes, endings and hundreds of branches, then adds it to your library. Pro exclusive · daily limit.',
  '剧本主题': 'Scenario theme',
  '想活一段什么样的人生？': 'What kind of life do you want to live?',
  '支线数量：': 'Branches: ',
  '数量越多越耐玩，但更耗时；由小愈 AI 深度生成，按聊天额度计。': 'More branches = more replayable, but takes longer; generated by Xiaoyu AI, billed per chat.',
  '正在构思世界观与支线剧情…': 'Designing the worldview and side branches…',
  // 人物志 / 人物卡（正文人名可点开看预设身份）——标签刻意用多字短语，避免字典子串替换误伤正文散文
  '人物志': 'Cast',
  '人物卡': 'Cast card',
  '看此人的预设身份': "See this person's preset identity",
  '本局登场过的人与他们的预设身份': 'Everyone who has appeared in this run and their preset identities',
  '与主角关系': 'Relation to you',
  '首次登场': 'First appears',
  '此人背景': 'Background',
  '这一局还没遇上什么有名字的人。': 'No one with a name has appeared in this run yet.',
  '此人的来历还没在剧情里写细，待后续回合补全。': "This person's background has not been fleshed out yet — later turns may add more.",
  '正在写支线剧情…': 'Writing side branches…',
  '正在生成…': 'Generating…',
  '开始生成': 'Start generating',
  '✎ 用表单创建剧本': '✎ Create a scenario with a form',
  '不用碰代码：填好下面的内容，我们会自动生成剧本文件。': 'No code needed: fill in the fields and we will build the scenario for you.',
  '标题': 'Title',
  '题材（可选）': 'Genre (optional)',
  '简介': 'Intro',
  '总回合上限（活到最后一回合的时长）': 'Max turns (how long one life lasts)',
  '属性（勇气/好感/修为…）': 'Attributes (courage, bond, cultivation…)',
  '初始值': 'Initial',
  '上限': 'Max',
  '开局身份（至少 1 个）': 'Openings (at least 1)',
  '开局时发生的事': 'What happens at the start',
  '结局（至少 1 个）': 'Endings (at least 1)',
  '某属性降到 0': 'An attribute drops to 0',
  '活到最后一回合': 'Reach the final turn',
  '尾声（可选）': 'Epilogue (optional)',
  '＋ 添加属性': '+ Add attribute',
  '＋ 添加开局': '+ Add opening',
  '＋ 添加结局': '+ Add ending',
  '取消': 'Cancel',
  '创建剧本': 'Create scenario',
  '请填写标题和简介': 'Please fill in a title and intro',
  '至少需要一个属性，且属性名不能为空': 'Need at least one attribute with a name',
  '至少需要一个开局身份，且身份名不能为空': 'Need at least one opening with a name',
  '至少需要一个结局': 'Need at least one ending',
  '剧本创建失败：': 'Failed to create scenario: ',
  '剧本导入失败': 'Scenario import failed',
  '剧本 id「': 'Scenario id "',
  '」与内置剧本冲突，请改用其他 id': '" conflicts with a built-in scenario. Please use another id.',
  '字段 ': 'Field ',
  '：(根)': ': (root)',
  // Setup
  '游玩模式': 'Play mode',
  '本地试玩': 'Local play',
  '引擎按内置剧情池随机演进，即点即玩、完全免费；每局不同，但剧情有限': 'The engine evolves from the built-in event pool — instant, free, different every run, but finite.',
  'AI 驱动': 'AI-driven',
  '由小愈 AI 实时编织独一无二的剧情与结局，支持自定义行动；每回合消耗 1 次聊天额度': 'Xiaoyu AI weaves a one-of-a-kind story and ending in real time, with custom actions; each turn costs 1 chat credit.',
  'AI 服务': 'AI service',
  'AI 由小愈驱动（DeepSeek）。每次回合消耗 1 次聊天额度，与聊一聊/角色扮演共用。': 'AI is powered by Xiaoyu (DeepSeek). Each turn costs 1 chat credit shared with chat & roleplay.',
  '选择开局身份': 'Choose your starting identity',
  '自设': 'Custom',
  '✎ 自定义身份': '✎ Custom identity',
  'AI 会据此身份演绎你的专属剧情与际遇': 'The AI weaves a story and fate shaped by this identity',
  '自己写一个角色：身份、性格、秘密、处境……': 'Write a character: identity, personality, secrets, circumstances…',
  '写下你的出身、性格与那点藏着的秘密': 'Describe your origins, personality, and that hidden secret',
  '立下你的目标（可选）': 'Set your ambition (optional)',
  'AI 会围绕它编织机遇与阻碍、推动或阻挠剧情，并在结局点明它最终实现、落空还是变质': 'The AI weaves opportunities and obstacles around it, and reveals at the ending whether it was fulfilled, dashed, or twisted.',
  '游戏会围绕它编织机遇与阻碍，让每个选择都有方向。留空则随遇而安。': 'The story weaves opportunities and obstacles around it, giving every choice a direction. Leave blank to drift.',
  '或者，自己写一个': 'Or write your own',
  '开始这段人生': 'Begin this life',
  '本地试玩从内置事件池取材，开局身份决定你会遇上哪些事件——三种身份走的是三条不同的线。切到「AI 驱动」还能自己写身份，由 AI 现编贴合你设定的剧情。': 'Local play draws from the built-in event pool; your starting identity decides which events you meet. Switch to AI-driven to write your own identity.',
  // Play
  '托管中：AI 正替你的角色演进': 'Auto-play: AI is advancing your character',
  '开启后由 AI 替你的角色自动抉择、自动演进': 'When on, the AI chooses and advances for you automatically',
  '停止托管': 'Stop auto-play',
  '交由 AI 托管': 'Let AI play',
  'AI 托管是 Pro 会员专属功能，升级 Pro 后即可使用': 'AI Auto-play is a Pro-only feature — upgrade to Pro to use it',
  'Pro 专属': 'Pro exclusive',
  'Pro 会员专属': 'Pro exclusive',
  '「AI 托管」是 Pro 会员专属功能——开启后 AI 会替你的角色自动抉择、自动演进，无需手动操作。升级 Pro 即可使用。': 'AI Auto-play is a Pro-only feature — turn it on and the AI will choose and advance the story for you automatically, no manual play needed. Upgrade to Pro to unlock it.',
  '去升级 Pro': 'Upgrade to Pro',
  '继续手动游玩': 'Continue playing manually',
  '连续托管已暂停': 'Auto-play paused',
  '已连续托管 15 回合。你可以再托管 15 回合，或挂机到底跑到今日额度用完。': 'Auto-played 15 turns in a row. Continue for 15 more, or let it run to the end (until today\u2019s limit).',
  '再托管 15 回合': 'Continue 15 more turns',
  '挂机到底': 'Run to the end',
  '已达': 'Reached the ',
  '上限，需晋阶突破方可提升': ' cap — advance to raise it further',
  '目标进度 · ': 'Ambition · ',
  '提升': '+',
  '降低': '−',
  '写下你想做的事，由 AI 裁定结果（Enter 提交，Shift+Enter 换行）': 'Write what you want to do — the AI will rule on the outcome (Enter to submit, Shift+Enter for newline)',
  '✎ 自己写一个行动…': '✎ Write your own action…',
  // Ending
  '点击放大徽章': 'Click to enlarge badge',
  '死亡': 'Death',
  '耗尽': 'Depleted',
  '气数已尽': 'Your fate is spent',
  '，你的人生就此画上句点': ' — and with it, your life draws to a close',
  '落幕': 'Curtain falls',
  '此生行至尽头，命途就此落幕': 'At the end of this life, the curtain falls',
  '生成命运卡，预览后复制/保存/分享': 'Create a Fate Card — preview, then copy / save / share',
  '分享命运卡': 'Share Fate Card',
  '命运卡预览': 'Fate Card preview',
  '复制卡图，直接粘进微信/聊天框发图': 'Copy the card image and paste it into WeChat / chat',
  '把命运卡保存到本地': 'Save the card to your device',
  '已复制图，去聊天框粘贴 ✓': 'Image copied — paste it into the chat ✓',
  '此环境不支持复制图，请用「保存图片」': 'This environment cannot copy images — use "Save image"',
  '已保存到本地 ✓': 'Saved to device ✓',
  '链接已复制 ✓': 'Link copied ✓',
  '复制失败，请手动选取': 'Copy failed — please select manually',
  '以同一段命途，从头再走一遍': 'Walk the same fate from the beginning',
  '回到卷首，另择一段人生': 'Return to the start and choose another life',
  // Archive（回看：自动封存替代手动存档）
  '← 返回卷首': '← Back to start',
  '命书阁': 'Archive',
  '回看 · 成就 · 结局图鉴': 'Rewind · Achievements · Endings gallery',
  '命运回看': 'Fate Rewind',
  '回看': 'Rewind',
  '命运抉择': 'Key Decision',
  '结局前': 'Before the Ending',
  '进行中封存': 'Saved Run',
  '命途尚未落笔。命运抉择与结局前会为你自动留下回看，随时回来重选。': 'No fate has been written yet. Key decisions and moments before an ending are saved automatically — come back and choose again anytime.',
  '进行中局已在上方列出，随时可继续；关键抉择与结局前会自动留下回看。': 'In-progress runs are listed above — continue anytime; key decisions and pre-ending moments are kept automatically.',
  '删除这个回看点？': 'Delete this checkpoint?',
  '」？': '"?',
  '尚未解锁的结局': 'Locked ending',
  '此结局的尾声唯有亲历方知，再走一遭吧。': 'The epilogue of this ending can only be known by living it — walk it again.',
  '结局 · ': 'Ending · ',
  '徽章 · ': 'Badge · ',
  '徽章「': 'Badge "',
  // Memoir
  '命途留影': 'Fate in frames',
  // ShareCardModal
  '分享挑战链接到': 'Share challenge link to ',
  '复制挑战链接（微信/小红书等无网页分享，靠这个或卡上二维码）': 'Copy challenge link (for WeChat / Xiaohongshu etc. without web sharing)',
  '分享到…': 'Share to…',
  '当前设备不支持系统分享，请先「保存图片」，再到对应 App 里上传。': 'System share isn’t supported here — please “Save image”, then upload it in the app.',
  // 通用回合单位（引擎数据）
  '载': 'year',
  '年': 'year',
  '月': 'month',
  '回合': 'turn',
  '命途 ': 'Fate ',
  '✦ 命运抉择': '✦ A Fateful Choice',
  // client 错误
  '小愈 AI 请求失败': 'Xiaoyu AI request failed',
  'AI 返回的数据格式不对': 'AI returned an invalid format',
  'API Key 无效或无权限（401），请检查配置': 'Invalid API key or no permission (401) — check your configuration',
  '请求过于频繁或额度不足（429），请稍候重试': 'Too many requests or out of quota (429) — please try again later',
  'AI 服务端错误（': 'AI server error (',
  '），请稍候重试': ') — please try again later',
  '请求失败（': 'Request failed (',
  '网络错误，或该服务不支持浏览器直连（CORS）。可在配置里打开「CORS 中转」再试一次。': 'Network error, or this service does not support direct browser access (CORS).',
  '发生错误：': 'Error: ',
  'AI 返回的数据格式不对 · ': 'AI returned an invalid format · ',
  // 文游补充（英文/简繁残留 → 跟随界面语言）
  '命运正在落笔…': 'Fate is being written…',
  '↓ 有新内容': '↓ New content',
  '点击跳过': 'Tap to skip',
  '尚未起步': 'Not started',
  '略有进展': 'Slight progress',
  '渐入佳境': 'Getting into it',
  '近在咫尺': 'Almost there',
  '已达成': 'Achieved',
  '未找到 API 配置，请回到卷首重新设置': 'No API configuration found — go back to the start to set it up',
  '复制失败：浏览器拒绝了剪贴板访问，请手动选择文本复制': 'Copy failed: the browser blocked clipboard access — select and copy manually',
  '点击看全图': 'Tap to view the full art',
  '查看大图': 'View the large image',
  '查看此节点配图': 'View this scene\u2019s art',
  '武侠江湖': 'Wuxia Jianghu',
  '三国谋士': 'Three Kingdoms Strategist',
  '校园青春': 'Campus Youth',
  '星际殖民': 'Interstellar Colony',
  '民国名伶': 'Republic-era Diva',
  '赛博朋克侦探': 'Cyberpunk Detective',
  '大航海海盗': 'Age of Sail Pirate',
  '生成失败': 'Generation failed',
  '关闭': 'Close',
  '搜索服务商…': 'Search providers…',
  '本地服务通常不需要': 'Usually not needed for local services',
  '（本地服务可留空）': '(leave blank for local services)',
  '模型名': 'Model name',
  '服务商（可搜索）': 'Provider (searchable)',
  'API 文档 ↗': 'API docs ↗',
  'Base URL（可改为代理或区域地址）': 'Base URL (can be a proxy or regional address)',
  '获取 Key ↗': 'Get key ↗',
  'API Key（本地服务可留空）': 'API key (can be blank for local services)',
  '模型（可搜索，也可直接输入任意模型名）': 'Model (searchable, or type any model name)',
  '思考强度': 'Thinking depth',
  '低': 'Low',
  '中': 'Medium',
  '高': 'High',
  '该服务商不支持关闭思考——「最低」发送它自己的最低值，仍会推理、仍会计费。调高通常更准确，但更慢、更耗额度。': 'This provider cannot fully disable thinking — "Lowest" sends its own lowest level, which still reasons and still costs. Higher is usually more accurate but slower and more expensive.',
  '自填地址不走中转：那台按域名白名单转发，够不着局域网 / 自建地址。遇到跨域（CORS）失败，要在你自己的服务端加响应头。': 'Self-hosted addresses do not use the relay: it forwards by domain whitelist, so it cannot reach LAN / self-hosted addresses. If CORS fails, add response headers on your own server.',
  'CORS 中转': 'CORS relay',
  '必须开': 'Required',
  '需要完整地址，包含 https://': 'Needs the full address, including https://',
  '我的故事': 'My Story',
  '日常 / 仙侠 / 悬疑…': 'Daily / Xianxia / Mystery…',
  '用一两句话介绍这个故事': 'Describe the story in a line or two',
  '属性名（如 勇气）': 'Attribute name (e.g. Courage)',
  '初始': 'Initial',
  '身份名（如 平凡上班族）': 'Identity name (e.g. an ordinary office worker)',
  '结局名（如 勇气耗尽）': 'Ending name (e.g. Courage spent)',
  '删除属性': 'Delete attribute',
  '删除开局': 'Delete opening',
  '用表单创建新剧本': 'Create a scenario with a form',
  // 存储/导入错误
  '进行中进度写入失败': 'Failed to save in-progress progress',
  '未命名': 'Untitled',
  '存档位写入失败': 'Failed to write save slot',
  '不是合法的 JSON 文件': 'Not a valid JSON file',
  '存档格式无效或已损坏': 'Save format is invalid or corrupted',
  // 首页导入/示例剧本
  '文件不是有效的 JSON，请下载示例剧本对照格式修改': 'The file is not valid JSON — download the example scenario and follow its format',
  '剧本格式校验未通过': 'Scenario format validation failed',
  '剧本': 'Scenario',
  '示例剧本.json': 'example-scenario.json',
  '我的第一个故事': 'My First Story',
  '日常': 'Daily',
  '一个关于勇气的小故事。': 'A little story about courage.',
  '勇气': 'Courage',
  '平凡的一天': 'An Ordinary Day',
  '你是一个普通的上班族，今天早上出门时遇到了一个需要帮助的陌生人。': 'You are an ordinary office worker; on the way out this morning you meet a stranger who needs help.',
  '你是一位温柔的文字人生模拟器，围绕玩家的选择展开剧情，用中文讲述，注意体现“勇气”属性的变化。': 'You are a gentle text life-simulator; weave the story around the player\u2019s choices, narrate in the interface language, and reflect changes in the "Courage" attribute.',
  '退缩': 'Back out',
  '勇气耗尽，你选择了退缩。但这只是一个开始。': 'Courage ran out and you chose to back out. But this is only the beginning.',
  '你遇到了一个需要帮助的陌生人。': 'You meet a stranger who needs help.',
  '上前帮忙': 'Step up to help',
  '陌生人感激地笑了。': 'The stranger smiles gratefully.',
  '犹豫着走开': 'Hesitate and walk away',
  '你低头快步走过。': 'You bow your head and hurry past.',
  '一次小小的选择': 'A small choice',
  // 字号档位（自建表单默认值/字号控制）
  '小': 'Small',
  '大': 'Large',
  '特大': 'Extra large',
  // 自建剧本默认值 / 校验错误
  '你在一如往常的清晨醒来，故事从这里开始。': 'You wake on a morning that feels just like any other — the story begins here.',
  '此生行至尽头': 'This life reaches its end',
  '勇气耗尽': 'Courage spent',
  '(根)': '(root)',
  '微博': 'Weibo',
  'QQ空间': 'Qzone',
  // Play 界面残留
  '目标': 'Goal',
  '托管中': 'Auto-play',
  '分享此刻': 'Share this',
  '退出本局': 'Quit run',
  '照此行事': 'Do as advised',
  '行囊': 'Satchel',
  '记忆': 'Memory',
  '托管中 · AI 正替你的角色做出抉择，点任意选项或「托管 ⏸」可随时接管': 'Auto-play · the AI is choosing for you; tap any option or "Auto-play ⏸" to take over anytime',
  // Ending 界面残留
  '轻触，揭晓此生结局': 'Tap to reveal this life\u2019s ending',
  '成就解锁': 'Achievement unlocked',
  '正在书写你的结局…': 'Writing your ending…',
  '本局为本地模式生成；填入 AI Key 可获得由大模型实时编织的独特剧情与结局。': 'This run was generated in local mode; add an AI key for a story woven live by the model.',
  '文字版分享卡 · 点开预览': 'Text sharing card · tap to preview',
  '分享命运卡 ⤴': 'Share Fate Card ⤴',
  '命途留影 ◷': 'Fate in frames ◷',
  '↻ 再活一世': '↻ Live again',
  '❖ 换个人生': '❖ Another life',
  '级': 'Grade ',
  '第 ': 'Turn ',
  '历经 ': 'Through ',
  '称号 ': 'Title: ',
  '已得成就 ': 'Achievements: ',
  '命运 · ': 'Fate · ',
  '千世书 · ': 'Thousand Lives · ',
  // 字号
  '字号': 'Font size',
  // Home 界面残留
  '📖 已历结局': '📖 Endings seen',
  '🏅 成就': '🏅 Achievements',
  '⬇ 下载示例剧本': '⬇ Download example scenario',
  // 其它弹窗
  '轻触关闭': 'Tap to close',
  '这一生尚未落笔，留影待续……': 'This life is not yet written — more frames to come…',
  '去开一段人生 →': 'Go start a life →',
  '删除': 'Delete',
  '删除这条游玩记录？该剧本的进行中进度将被清空，无法恢复。': 'Delete this play record? This scenario\u2019s in-progress progress will be cleared and can\u2019t be recovered.',
  '删除游玩记录': 'Delete play record',
  '同时删除该剧本在命书阁的回看': 'Also delete this scenario\u2019s Archive checkpoints',
  '（命书阁的结局图鉴与成就不受影响）': '(Archive endings & achievements are unaffected)',
  '圆满': 'Full circle',
  '命运卡生成失败，请重试。': 'Failed to generate the Fate Card — please retry.',
  '正在生成命运卡…': 'Generating your Fate Card…',
  '复制图片 ⎘': 'Copy image ⎘',
  '保存图片 ⤓': 'Save image ⤓',
  '分享链接到': 'Share link to',
  '复制链接 🔗': 'Copy link 🔗',
  '社交分享自带题材封面预览；想发带你高光时刻的个性化命运卡，请用「复制图片」粘贴，或让对方扫码。微信/小红书无网页分享接口，同样靠复制图/扫码。': 'Social shares come with a theme-cover preview; to send a personalized Fate Card of your highlight, use "Copy image" to paste, or have the other person scan the code. WeChat / Xiaohongshu have no web-share interface — use copy-image / scan.',
  '关闭（更快更省）': 'Off (faster & cheaper)',
  '最低': 'Lowest',
  '已开启': 'On',
  '直连': 'Direct',
  '该服务商不给浏览器发跨域头，直连发不出请求 —— 这一项已默认开启。': 'This provider doesn\u2019t send CORS headers to browsers, so direct requests fail — this is on by default.',
  '请求默认从浏览器直连；遇到跨域（CORS）或 403 错误时开启它转发一次。': 'Requests go directly from the browser by default; enable this to relay once when you hit CORS or 403 errors.',
  ' 开启后你的 API Key 与完整 prompt 会经过这台中转再到服务商；它只转发不留存，在意的话可改成自建地址（见文档）。': ' When enabled, your API key and full prompt pass through this relay to the provider; it only forwards and stores nothing. If you care, set a self-hosted address (see docs).',
  // 回看载入/退出（自动封存 era 文案）
  '将回到所选回看点继续；当前进行中进度已自动封存为回看点，不会丢失。确定？': 'You will resume from the chosen checkpoint; your current in-progress run is auto-saved as a checkpoint and won\u2019t be lost. Continue?',
  '退出本局会放弃当前这局（自动保存的进行中进度随之清空，命书阁里的回看点不受影响），确定退出？': 'Quitting discards this run (its auto-saved progress will be cleared; Archive checkpoints are unaffected). Quit?',
  '退出当前这局并清空其自动进度（命书阁回看点不受影响）': 'Quit this run and clear its auto progress (Archive checkpoints are unaffected)',
};

/** 剧本 UI 可见字段扁平化：从源剧本（zh）+ 英文词典反查，得到 zh→en 数据映射 */
const FLAT_DATA: Record<string, string> = (() => {
  const flat: Record<string, string> = {};
  for (const sc of builtinScenarios) {
    const en = (SCENARIO_EN as any)[sc.id];
    if (!en) continue;
    const put = (zh: string | undefined, e: string | undefined) => {
      if (zh && e && !flat[zh]) flat[zh] = e;
    };
    put(sc.title, en.title);
    put(sc.genre, en.genre);
    put(sc.intro, en.intro);
    put(sc.turnUnit, en.turnUnit);
    for (const a of sc.attributes || []) {
      const ea = (en.attributes || []).find((x: any) => x.key === a.key);
      put(a.name, ea?.name);
      (a.bands || []).forEach((b, i) => put(b.label, ea?.bands?.[i]));
    }
    (sc.openings || []).forEach((o, i) => {
      put(o.name, en.openings?.[i]?.name);
      put(o.prompt, en.openings?.[i]?.prompt);
    });
    (sc.ambitions || []).forEach((amb, i) => put(amb, en.ambitions?.[i]));
    (sc.endings || []).forEach((e, i) => put(e.tone, en.endings?.[i]?.tone));
  }
  return flat;
})();

/** 全量 zh→en 扁平词典（静态文案 + 剧本数据 + 物品名等界面可见中文） */
export const FLAT_EN: Record<string, string> = { ...WY_EN, ...FLAT_DATA, ...SCENARIO_ITEMS_EN };

const SKIP = new Set(['SCRIPT', 'STYLE', 'TEXTAREA', 'INPUT', 'CODE', 'PRE', 'NOSCRIPT']);
const HAN = /[\u4e00-\u9fff]/;
const PHRASES = Object.keys(FLAT_EN).sort((a, b) => b.length - a.length);

function replacePhrases(text: string): string {
  if (!HAN.test(text)) return text;
  let out = text;
  for (const zh of PHRASES) {
    if (!zh) continue;
    const en = FLAT_EN[zh];
    if (out.includes(zh)) out = out.split(zh).join(en);
  }
  return out;
}

/**
 * 文本节点转换器（单一实例）：
 * - en：用 FLAT_EN 词典做子串替换
 * - zh-TW：用 opencc cn→tw 转换（跟随主 App 语言，替代原文游内简繁按钮）
 * - zh-CN：源语言，不转换
 * 顺带把 <html lang> 同步为当前语言（原 LangToggle 职责）。
 */
let s2t: ((s: string) => string) | null = null;
async function ensureS2T(): Promise<(s: string) => string> {
  if (!s2t) {
    const OpenCC = (await import('opencc-js')) as unknown as {
      Converter: (o: { from: string; to: string }) => (s: string) => string;
    };
    s2t = OpenCC.Converter({ from: 'cn', to: 'tw' });
  }
  return s2t;
}

const ATTR_KEYS: Array<'placeholder' | 'title' | 'aria-label'> = ['placeholder', 'title', 'aria-label'];

function convAttrs(el: Element, conv: (s: string) => string) {
  for (const k of ATTR_KEYS) {
    const v = el.getAttribute(k);
    if (v && HAN.test(v)) {
      const c = conv(v);
      if (c !== v) el.setAttribute(k, c);
    }
  }
}

function convText(t: Text, conv: (s: string) => string) {
  const p = t.parentElement;
  if (!p || SKIP.has(p.tagName) || p.isContentEditable) return;
  const v = t.nodeValue;
  if (v && HAN.test(v)) {
    const c = conv(v);
    if (c !== v) t.nodeValue = c;
  }
}

function convTree(root: Node, conv: (s: string) => string) {
  if (root.nodeType === Node.TEXT_NODE) return convText(root as Text, conv);
  if (root.nodeType !== Node.ELEMENT_NODE) return;
  convAttrs(root as Element, conv);
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT | NodeFilter.SHOW_ELEMENT);
  const nodes: Node[] = [];
  let n: Node | null;
  while ((n = walker.nextNode())) nodes.push(n);
  for (const nd of nodes) {
    if (nd.nodeType === Node.TEXT_NODE) convText(nd as Text, conv);
    else convAttrs(nd as Element, conv);
  }
}

/** 挂到文游 App 内：按主 App 语言自动转换文游文本（en 词典 / zh-TW opencc / zh-CN 源）。
 *  lang 由外层 WenyouPage 注入（跟随主 App 语言）；语言切换时本组件重建 observer 并重转
 *  渲染层（<main key={lang}> 已重挂载为简体源），因此不再需要整棵 App 重挂载 ——
 *  游戏进度（screen/session）留在顶层不丢失。 */
export function WyLangSync({ lang }: { lang?: string }) {
  const obs = useRef<MutationObserver | null>(null);
  useEffect(() => {
    const current = lang ?? getLang();
    const root = document.getElementById('root');
    if (!root) return;
    try {
      document.documentElement.lang =
        current === 'en' ? 'en' : current === 'zh-TW' ? 'zh-Hant' : 'zh-Hans';
    } catch { /* 忽略 */ }
    if (current === 'zh-CN') return;
    let live = true;
    let conv: (s: string) => string = current === 'en' ? replacePhrases : (s) => s;
    const ensure = current === 'zh-TW' ? ensureS2T() : Promise.resolve(conv);
    ensure.then((c) => {
      if (!live) return;
      conv = c;
      const reconnect = () =>
        obs.current?.observe(root, { subtree: true, childList: true, characterData: true, attributes: true, attributeFilter: [...ATTR_KEYS] });
      obs.current = new MutationObserver((muts) => {
        obs.current?.disconnect();
        for (const m of muts) {
          if (m.type === 'characterData') convText(m.target as Text, conv);
          else if (m.type === 'attributes') convAttrs(m.target as Element, conv);
          else m.addedNodes.forEach((nd) => convTree(nd, conv));
        }
        reconnect();
      });
      convTree(root, conv);
      reconnect();
    });
    return () => {
      live = false;
      obs.current?.disconnect();
    };
  }, [lang]);
  return null;
}
